// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace BlazingDocumentor
{
    internal sealed partial class Vsix
    {
        public const string Id = "BlazingDocumentor.f17b76b7-e7e4-467f-80bc-1fd2fdf1663c";
        public const string Name = "BlazingDocumentor";
        public const string Description = @"An automated C# Documentation Comment generator.";
        public const string Language = "en-US";
        public const string Version = "1.2.3";
        public const string Author = "Oliver Schmidt";
        public const string Tags = "";
    }
}
